### ISSUE TITLE
1.11 Checklist

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#72]
- [x] Initial Errors

- [x] ItemStack Nulls

- [x] Lowercase Resources

- [x] Fix Missing Resources (Missing Textures/Names)

- [x] Fix Crashes

- [x] Fix JEI

- [x] Ensure Mod Is Playable

- [x] Improve Voidic Infuser and Heimdall GUIs

- [x] Fix Macerator GUI progress visual

- [x] Fix GUI Container Shift Clicking

- [x] Voidic Power Item Durability Bar Color
